### ISSUE TITLE
AttributeError: module 'sdmetrics' has no attribute 'single_table' when importing SDgym

### ISSUE THREAD

**Issue by jpcottrell** [sdv-dev/SDGym#117]
* SDGym version: 0.3.1
* Python version: 3.7.4
* Operating System: Mac OS Mojave 10.14.6

### Description

Tried to import SDgym into a jupyter notebook for the first time after install. 

Error message: "AttributeError: module 'sdmetrics' has no attribute 'single_table'"

sdmetrics is fully installed with latest version

**Comment by npatki** [comment]
Hi, since this issue was filed around 2 years ago for an older version of SDGym, I'm going to mark it as stale.

Since 2021, we've significantly improved and updated the SDGym library. You can view the docs and installation instructions [on this website](https://docs.sdv.dev/sdgym/installation). If you're still having issues, please feel free to file a new issue. Thanks!
