### ISSUE TITLE
when I use 'benchmark(synthesizer.fit_sample)', KeyError: 'structure' happens.

### ISSUE THREAD

**Issue by Zhengxuru** [sdv-dev/SDGym#19]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhengxr/anaconda3/lib/python3.7/site-packages/sdgym/benchmark.py", line 38, in benchmark
    scores = evaluate(train, test, synthesized, meta)
  File "/home/zhengxr/anaconda3/lib/python3.7/site-packages/sdgym/evaluate.py", line 366, in evaluate
    performance = evaluator(synthesized_data, test, metadata)
  File "/home/zhengxr/anaconda3/lib/python3.7/site-packages/sdgym/evaluate.py", line 297, in _evaluate_bayesian_likelihood
    structure_json = json.dumps(metadata['structure'])
KeyError: 'structure'

**Comment by pawelkuk** [comment]
As you call benchmark in the demo it downloads the required datasets from here: http://sdgym.s3.amazonaws.com/index.html

There is a zip folder with the required json structure files.

**Comment by csala** [comment]
Hi @Zhengxuru, thanks for reporting this.

The `structure` key was indeed missing in some of the demo datasets that are hosted in the S3 bucket, and existed only inside the SDGymBenchmarkData.zip file, as @pawelkuk pointed out (thanks!).

This is because the way the data is loaded for the benchmark was changed at some point and the datasets that require the structure entry were not properly updated in S3.

We just uploaded them again, so now it should work without issues.

Can you try deleting your `/home/zhengxr/anaconda3/lib/python3.7/site-packages/sdgym/data` (so the new datasets are re-downloaded) and trying again, @Zhengxuru ?

**Comment by Zhengxuru** [comment]
Thanks! @pawelkuk @csala

**Comment by csala** [comment]
Closing this issue, as it as already been resolved.
