### ISSUE TITLE
PrivBayes

### ISSUE THREAD

**Issue by dionman** [sdv-dev/SDGym#227]
Has PrivBayes been removed from recent versions of the library?

**Comment by npatki** [comment]
Hi @dionman, in recent versions of the SDGym library we have been focused on providing you with a more robust and reliable framework. We've prioritized integrations with the [SDV synthesizers](https://docs.sdv.dev/sdv) as well as giving you the ability [easily include your own, custom synthesizers](https://docs.sdv.dev/sdgym/customization/synthesizers/custom-synthesizers).

So unfortunately, the `PrivBayes` implementation is not yet included. Do you need this synthesizer? If so, we can treat this as a feature request. To help us prioritize, it would be great if you could provide more information about your use case and why it's needed.

Until then, it should be possible to retrofit the `PrivBayes` code and create your own custom synthesizer. As long as it follows the [framework](https://docs.sdv.dev/sdgym/customization/synthesizers/custom-synthesizers), you should be able to use it with all the other SDGym features.

**Comment by npatki** [comment]
Hello, I'm closing off this issue since it has been inactive for some time. Please feel free to reply if there is more to discuss and we can always reopen the issue.

Alternatively, you are welcome to file a new feature request for adding in `PrivBayes`. We prioritize new requests by demand and importance to your project, so any other information about your usage would be helpful. Thanks.
