### ISSUE TITLE
ImportError: cannot import name 'Metadata' from 'sdv' 

### ISSUE THREAD

**Issue by kiransview** [sdv-dev/SDGym#243]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDGym version: Latest
* Python version: 3.9
* Operating System: Windows 11

### Error Description

While i execute the below command
import sdgym
print(sdgym.__version__)

getting the error as mentioned in subject with the SDV __init__ python file

**Comment by npatki** [comment]
Hi @kiransview, thanks for reporting. 

This seems to be due to the (known) issue #246. Give that a read and let me know if it solves the error. 

BTW in order to get the version, you will need to copy the code exactly as shown [in the documentation](https://docs.sdv.dev/sdgym/installation#troubleshooting). Note that there are two underscores before and after the word `version`.

```python
print(sdgym.__version__)
```

**Comment by npatki** [comment]
Hi @kiransview, we just released a new version of [SDGym 0.7.0](https://github.com/sdv-dev/SDGym/releases/tag/v0.7.0), which should fix the issue. 

Please upgrade your SDGym library and let us know if you are still encountering this problem. (Feel free to reply here and we will reopen the issue to investigate.)
