### ISSUE TITLE
Benchmarking integer data

### ISSUE THREAD

**Issue by sbrugman** [sdv-dev/SDGym#48]
When benchmarking real datasets, sdgym now differentiates between continuous, categorical and ordinal data. The continuous data can be real or integer (e.g. Age). Currently, the synthesizers are allowed to produce real-valued features for integer-valued columns that are used as features to train the models. It would make sense to distinguish between these types and restrict the range that synthesized features for integer columns can take. @csala Would you agree that this change is an improvement to the benchmark? (If so, I can contribute a PR)

**Comment by npatki** [comment]
Hello, I realize it's been a few years since this issue was filed. Since 2020, we've significantly updated the SDGym's usage/API and streamlined the functionality. 

As a result, we are relying on the [SDV library](https://docs.sdv.dev/sdv) for a majority of our synthesizer logic. I believe that by default, all synthesizers enforce the min/max values and rounding scheme that they observe during the `fit` process. So if you have a discrete column of integers that is in the range `[1, 10]`, the synthesized data is guaranteed to only include those values.

I'm going to mark this issue as (more-or-less) resolved since we've made those changes. If you do have any more follow-ups, feel free to file a new issue. We can use that to discuss updates to the latest version of SDGym.

For more information, see the [updated, SDGym docs website](https://docs.sdv.dev/sdgym).
