### ISSUE TITLE
Big bug at class LegacySingleTableBaseline(SingleTableBaseline)

### ISSUE THREAD

**Issue by dungdinhanh** [sdv-dev/SDGym#68]
* SDGym version:
* Python version:
* Operating System:

### Description

When generating data, the class LegacySingleTableBaseline transforms labels into numbers. However, after transforming, the authors do not rearrange the columns. This makes the model apply the one-hot encoding scheme on continuous columns and Gaussian Mixtures models for categorical columns during training. 

### What I Did
I think you could fix the bugs at the line 131 at synthesizers/base.py from: model_data = ht.transform(real_data) to model_data = ht.transform(real_data)[columns].

The bug will be solved.

Thanks

**Comment by csala** [comment]
Thanks for reporting this @dungdinhanh !

Let me have a look at it and confirm both the bug and the solution.

**Comment by npatki** [comment]
Hi all,

Since this issue was filed, we have significantly improved and refactored the SDGym code so I'm marking this as obsolete. 

In particular, note that SDGym [no longer transforms the data](https://github.com/sdv-dev/SDGym/blob/master/sdgym/synthesizers/base.py#L41). The underlying synthesizer is expected to handle the logic, so with any SDV synthesizer this transformations happens in the SDV library.
